/*
 * One description of this work, written into the two files that read it.
 *
 * `CITATION.cff` is what GitHub turns into a "Cite this repository" button and
 * what reference managers parse. `.zenodo.json` is what Zenodo reads when it
 * archives a published release and mints a DOI. They want the same facts in
 * different shapes, and keeping two hand-edited copies of an author list is how
 * a DOI ends up crediting a slightly different person than the citation button.
 *
 * So both are generated from `WORK` below, and `--check` fails if either file on
 * disk has drifted from it. CI runs the check; a person runs it without the flag
 * to regenerate.
 *
 * No YAML library. `js-yaml` is present only as a transitive dependency of
 * something else, and a repository script that quietly relies on one of those
 * breaks the day that dependency changes its own tree. Writing the file is a
 * template; the only reason to parse YAML would be to read back what this wrote.
 *
 * ## Two shapes for the same identifier
 *
 * CFF wants an ORCID as the full `https://orcid.org/…` URL. Zenodo wants the
 * bare `0000-0002-…`. Getting that backwards is silently accepted by both and
 * produces an unlinked author on one side, which is the kind of error nobody
 * reports because nothing looks broken.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const WORK = {
  title: 'Agbrte — an agent workbench with durable, bridge-owned sessions',
  message: 'If you use this software or its design in academic or patent work, please cite it.',
  repository: 'https://github.com/YounghyeonPark/agbrte',
  license: 'Apache-2.0',
  author: {
    family: 'Park',
    given: 'Younghyeon',
    email: 'ypark.dev@gmail.com',
    /** Bare form. The two renderers below add or omit the URL prefix. */
    orcid: '0000-0002-4733-5049',
  },
  keywords: [
    'agent',
    'llm',
    'durable-sessions',
    'event-sourcing',
    'remote-execution',
    'electron',
  ],
  abstract: [
    'An agent workbench in which sessions belong to a per-workspace host process',
    'rather than to the window watching them. The host owns the append-only event',
    'log and the permission gate, so a run survives the app closing, is reachable',
    'from a second machine, and can execute on a remote target over SSH while the',
    'interface stays local. Includes a transport layer that refuses localities it',
    'has not implemented rather than silently running work elsewhere, and a',
    'capability model that distinguishes what an adapter declares from what has been',
    'observed.',
  ],
};

/**
 * An ORCID's last character is an ISO 7064 mod 11-2 checksum over the other
 * fifteen. Checked on every run rather than once at the keyboard, because a
 * wrong identifier in citation metadata is copied onward rather than noticed.
 */
function assertOrcid(orcid) {
  const digits = orcid.replace(/-/g, '');
  let total = 0;
  for (const ch of digits.slice(0, 15)) total = ((total + Number(ch)) * 2) % 11;
  const remainder = (12 - (total % 11)) % 11;
  const expected = remainder === 10 ? 'X' : String(remainder);
  if (digits[15] !== expected) {
    throw new Error(`ORCID ${orcid} fails its checksum: expected ${expected}, found ${digits[15]}`);
  }
}

function cff() {
  const { author: a } = WORK;
  return `# Generated by scripts/citation.mjs — edit that file, not this one.
#
# Read by GitHub, which turns it into a "Cite this repository" button, and by
# Zenodo, reference managers and citation tooling.
cff-version: 1.2.0
title: ${JSON.stringify(WORK.title)}
message: ${JSON.stringify(WORK.message)}
type: software
authors:
  - family-names: ${a.family}
    given-names: ${a.given}
    email: ${a.email}
    # The full URL form, which is what the CFF schema expects and what GitHub
    # renders as a link. Zenodo wants the bare identifier; see .zenodo.json.
    orcid: "https://orcid.org/${a.orcid}"
repository-code: ${JSON.stringify(WORK.repository)}
license: ${WORK.license}
abstract: >-
${WORK.abstract.map((line) => `  ${line}`).join('\n')}
keywords:
${WORK.keywords.map((k) => `  - ${k}`).join('\n')}
`;
}

function zenodo() {
  const { author: a } = WORK;
  return `${JSON.stringify(
    {
      // Zenodo has no comment syntax, so the pointer back lives in the
      // description's absence of one — `scripts/citation.mjs` is the source.
      upload_type: 'software',
      title: WORK.title,
      description: WORK.abstract.join(' '),
      // Bare identifier here, URL in the CFF. Zenodo silently accepts the URL
      // form and then fails to link the profile.
      creators: [{ name: `${a.family}, ${a.given}`, orcid: a.orcid }],
      license: WORK.license,
      keywords: WORK.keywords,
      related_identifiers: [
        { identifier: WORK.repository, relation: 'isSupplementTo', scheme: 'url' },
      ],
    },
    null,
    2,
  )}\n`;
}

assertOrcid(WORK.author.orcid);

const files = [
  ['CITATION.cff', cff()],
  ['.zenodo.json', zenodo()],
];

if (process.argv.includes('--check')) {
  let stale = 0;
  for (const [name, wanted] of files) {
    let found = '';
    try {
      found = readFileSync(resolve(root, name), 'utf8').replace(/\r\n/g, '\n');
    } catch {
      found = '';
    }
    if (found !== wanted) {
      console.log(`${name} is out of date — run \`node scripts/citation.mjs\``);
      stale += 1;
    }
  }
  if (stale === 0) console.log('citation metadata is current');
  process.exitCode = stale === 0 ? 0 : 1;
} else {
  for (const [name, contents] of files) {
    writeFileSync(resolve(root, name), contents);
    console.log(`wrote ${name}`);
  }
}
